# Generated by Django 5.2.12 on 2026-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quiz_lesson_quiz_course_quiz_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes (time limit for this quiz)'),
        ),
    ]
