# Generated by Django 5.2.12 on 2026-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_url', models.URLField(max_length=500)),
                ('attachment_name', models.CharField(max_length=255)),
                ('attachment_type', models.IntegerField(choices=[(1, 'File'), (2, 'Link')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.IntegerField(choices=[(1, 'Everyone'), (2, 'Only Invited by Instructor/Admin')], default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=1)),
                ('total_lesson', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0, help_text='Duration in minutes or seconds')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, help_text='JSON data using editor.js', null=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
    ]
