# Generated by Django 5.2.12 on 2026-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
